version: '3.8'
services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y